# Label for this particular deployed instance
# Results in a name like "osdf-origin-[Instance]"
Instance: ""


Topology:
  ResourceName: "TestOrigin"
  FQDN: "testorigin.example.net"

PublicOrigin:
  Enabled: true
  # All exports are relative to /xcache/namespace
  Exports:
    - "/VONAME/PUBLIC"
    #- "/publicexport2"
    #- "/publicexport3"
  ## Uncomment and fill out for local additions to the Authfile
  # AuthfileLocal: |-
  #  ...


AuthOrigin:
  Enabled: false
  # All exports are relative to /xcache/namespace
  Exports:
    - "/VONAME/PROTECTED"
    #- "/authexport2"
    #- "/authexport3"
  ## Uncomment and fill out for local additions to the Authfile
  # AuthfileLocal: |-
  #   ...
  ## Uncomment and fill out for local additions to scitokens.conf, e.g. extra issuers.
  # ScitokensConfLocal: |-
  #   ...

DataVolumes:
  # All MountPaths are relative to /xcache/namespace
  - Name: "xcache-namespace"
    MountPath: "/"
    # Choose one:
    #ClaimName: "osdf-origin-data"
    #HostPath: "/mnt/stash/origin-data"

## Uncomment to persist /var/log/xrootd
# XrootdLogVolume:
#   ClaimName:


# Host Certificate and Key
# run 'slate secret create --help' for usage
# Leaving this empty will disable reporting to the central collector.
HostCredentials:
  # Name of the secret containing a host key and certificate in
  # "tls.key" and "tls.crt", respectively.
  HostCertKeySecret: null

# Resources:
#   Requests:
#     CPU: 1
#     Memory: 2Gi
#   Limits:
#     CPU: 1
#     Memory: 2Gi

Containers:
  Origin:
    # "docker.io" and "hub.opensciencegrid.org" are the allowed registries.
    Registry: "hub.opensciencegrid.org"
    # The organization; "matyasosg" and "opensciencegrid" are the allowed organizations.
    Organization: opensciencegrid
    # The tag to pull; the image is "$ORGANIZATION/stash-origin"
    Tag: 3.6-release
    ImagePullPolicy: Always

### SLATE-START ###
SLATE:
  Instance:
    ID: "untagged"
### SLATE-END ###
