# Label for this particular deployed instance
# Results in a name like "osdf-origin-[Instance]"
Instance: ""

nameOverride: ""
fullnameOverride: ""

topologyResourceName: "TestOrigin"
topologyFQDN: "testorigin.example.net"

# run 'slate secret create --help' for usage
# hostCertKeySecret is the name of the secret containing a host key and certificate in
# "tls.key" and "tls.crt", respectively.
hostCertKeySecret: null

publicOrigin:
  enabled: false
  port: 1094
  ## Uncomment and list at least one namespace to export
  ## All exports are relative to /xcache/namespace
  #exports:
  #  - "/VONAME/PUBLIC"
  #  - "/publicexport2"
  #  - "/publicexport3"
  ## Uncomment and fill out for local additions to the Authfile
  # authfileLocal: |-
  #  ...


authOrigin:
  enabled: false
  port: 1095
  ## Uncomment and list at least one namespace to export
  ## All exports are relative to /xcache/namespace
  #exports:
  #  - "/VONAME/PROTECTED"
  #  - "/authexport2"
  #  - "/authexport3"
  ## Uncomment and fill out for local additions to the Authfile
  # authfileLocal: |-
  #   ...
  ## Uncomment and fill out for local additions to scitokens.conf, e.g. extra issuers.
  # scitokensConfLocal: |-
  #   ...

# dataVolumes:
  # All MountPaths are relative to /xcache/namespace
  #- name: "xcache-namespace"
    #mountPath: "/"
    # Choose one:
    #claimName: "osdf-origin-data"
    #hostPath: "/mnt/stash/origin-data"

## Uncomment and fill out for extra xrootd config lines, added before the OSG-provided config
# extraXrootdConfigBefore: |-
#   ...

## Uncomment and fill out for extra xrootd config lines, added after the OSG-provided config
# extraXrootdConfigAfter: |-
#   ...


livenessProbeEnabled: true


## Uncomment to persist /var/log/xrootd
xrootdLogVolumeClaimName: null


image:
  # "docker.io" and "hub.opensciencegrid.org" are the allowed registries.
  registry: "hub.opensciencegrid.org"
  # The organization; "matyasosg", "osgpreview", and "opensciencegrid" are the allowed organizations.
  organization: opensciencegrid
  # The tag to pull; the image is "$ORGANIZATION/stash-origin"
  tag: 3.6-release
  pullPolicy: Always

# Resource requests/limits for the origin container
# resources:
#   requests:
#     cpu: 1
#     memory: 2Gi
#   limits:
#     cpu: 1
#     memory: 2Gi

# Extra environment variables for the origin container
# extraEnv:
#   - name: ...
#     value: "..."


# Optional node lock for the deployment
nodeName: null

# Optional nodeSelector block for the deployment
nodeSelector: {}

# Optional tolerations block for the deployment
tolerations: []

# Optional affinity block for the deployment
affinity: {}

# Optional annotations block for the service
serviceAnnotations: {}

## A secret containing the S3 keys for the experimental S3 plugin
# s3KeysSecret: null

### SLATE-START ###
SLATE:
  Instance:
    ID: "untagged"
### SLATE-END ###
