# Label for this particular deployed instance
# Results in a name like "osdf-origin-[Instance]"
Instance: ""

Topology:
  ResourceName: "TestOrigin"
  FQDN: "testorigin.example.net"

PublicOrigin:
  Enabled: true
  # All exports are relative to /xcache/namespace
  Exports:
    - "/VONAME/PUBLIC"
    #- "/publicexport2"
    #- "/publicexport3"
    
AuthOrigin:
  Enabled: false
  # All exports are relative to /xcache/namespace
  Exports:
    - "/VONAME/PROTECTED"
    #- "/authexport2"
    #- "/authexport3"

DataVolumes:
  # All MountPaths are relative to /xcache/namespace
  - Name: "xcache-namespace"
    MountPath: "/"
    ClaimName: "osdf-origin-data"

# Host Certificate and Key
# run 'slate secret create --help' for usage
# Leaving this empty will disable reporting to the central collector.
HostCredentials:
  # Name of the secret containing a host key and certificate in
  # "tls.key" and "tls.crt", respectively.
  HostCertKeySecret: null

Resources:
  CPU: 2
  Memory: 1Gi

Containers:
  Origin:
    # "docker.io" and "hub.opensciencegrid.org" are the allowed registries.
    Registry: "hub.opensciencegrid.org"
    # The tag to pull; the image is "opensciencegrid/stash-origin"
    Tag: 3.6-release
    ImagePullPolicy: Always

### SLATE-START ###
SLATE:
  Instance:
    ID: "untagged"
### SLATE-END ###
