apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "osdf-origin.fullname" . }}
  labels:
    app: {{ template "osdf-origin.name" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "osdf-origin.name" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance | quote }}

  template:
    metadata:
      labels:
        app: {{ template "osdf-origin.name" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance | quote }}

    spec:
      volumes:
      {{- range .Values.DataVolumes }}
      - name: {{ .Name }}
        {{- if and (not (empty .ClaimName)) (not (empty .HostPath)) }}
          {{- fail "Specify ClaimName or HostPath, not both" -}}
        {{- else if .ClaimName }}
        persistentVolumeClaim:
          claimName: {{ .ClaimName }}
        {{- else if .HostPath }}
        hostPath:
          path: {{ .HostPath }}
          type: Directory
        {{- else }}
          {{- fail "Specify either ClaimName or HostPath" -}}
        {{- end }}
      {{- end }}

      {{- if .Values.HostCredentials.HostCertKeySecret }}
      - name: hostcertkey
        secret:
          secretName: {{ .Values.HostCredentials.HostCertKeySecret }}
          items:
          - key: tls.crt
            path: hostcert.pem
            mode: 0o644
          - key: tls.key
            path: hostkey.pem
            mode: 0o400
      {{- end }}
      - name: config
        configMap:
          name: {{ template "osdf-origin.fullname" . }}

      {{- if .Values.XrootdLogVolume }}
      - name: logs
        persistentVolumeClaim:
          claimName: {{ .Values.XrootdLogVolume.ClaimName }}
      {{- end }}

      # end volumes

      containers:
        - name: origin
          image: "{{ template "osdf-origin.origin-registry" . }}/{{ template "osdf-origin.origin-organization" . }}/stash-origin:{{ .Values.Containers.Origin.Tag }}"
          imagePullPolicy: {{ .Values.Containers.Origin.ImagePullPolicy }}
          env:
          - name: XC_RESOURCENAME
            value: "{{ .Values.Topology.ResourceName }}"
          - name: ORIGIN_FQDN
            value: "{{ .Values.Topology.FQDN }}"
          - name: XC_ROOTDIR
            value: "/xcache/namespace"
        {{- if .Values.PublicOrigin.Exports }}
          - name: XC_PUBLIC_ORIGIN_EXPORT
            value: "{{ first .Values.PublicOrigin.Exports }}"
        {{- end }}
        {{- if .Values.AuthOrigin.Exports }}
          - name: XC_AUTH_ORIGIN_EXPORT
            value: "{{ first .Values.AuthOrigin.Exports }}"
        {{- end }}

          {{- if .Values.Resources }}
          resources:
            {{- if .Values.Resources.Requests }}
            requests:
              {{- if .Values.Resources.Requests.CPU }}
              cpu: "{{ .Values.Resources.Requests.CPU }}"
              {{- end }}
              {{- if .Values.Resources.Requests.Memory }}
              memory: "{{ .Values.Resources.Requests.Memory }}"
              {{- end }}
            {{- end }}
            {{- if .Values.Resources.Limits }}
            limits:
              {{- if .Values.Resources.Limits.CPU }}
              cpu: "{{ .Values.Resources.Limits.CPU }}"
              {{- end }}
              {{- if .Values.Resources.Limits.Memory }}
              memory: "{{ .Values.Resources.Limits.Memory }}"
              {{- end }}
            {{- end }}
          {{- end }}
          livenessProbe:
            tcpSocket:
              {{- if .Values.AuthOrigin.Enabled }}
              port: 1095
              {{- else if .Values.PublicOrigin.Enabled }}
              port: 1094
              {{- end }}
            initialDelaySeconds: 600
            periodSeconds: 60
          ports:
            {{- if .Values.AuthOrigin.Enabled }}
            - containerPort: 1095
              hostPort: 1095
              protocol: TCP
            {{- end }}
            {{- if .Values.PublicOrigin.Enabled }}
            - containerPort: 1094
              hostPort: 1094
              protocol: TCP
            {{- end }}
          volumeMounts:
            {{- range .Values.DataVolumes }}
            - mountPath: /xcache/namespace{{ .MountPath }}
              name: {{ .Name }}
            {{ end }}
            {{- if .Values.HostCredentials.HostCertKeySecret }}
            - mountPath: /etc/grid-security/hostcert.pem
              name: hostcertkey
              subPath: hostcert.pem
            - mountPath: /etc/grid-security/hostkey.pem
              name: hostcertkey
              subPath: hostkey.pem
            {{ end }}
            - mountPath: /etc/xrootd/config.d/extra_exports.cfg
              name: config
              subPath: extra_exports.cfg
            {{- if .Values.PublicOrigin.AuthfileLocal }}
            - mountPath: /run/stash-origin/Authfile.local
              name: config
              subPath: stash-origin-Authfile.local
            {{ end }}
            {{- if .Values.AuthOrigin.AuthfileLocal }}
            - mountPath: /run/stash-origin-auth/Authfile.local
              name: config
              subPath: stash-origin-auth-Authfile.local
            {{ end }}
            {{- if .Values.AuthOrigin.ScitokensConfLocal }}
            - mountPath: /run/stash-origin-auth/scitokens.conf.local
              name: config
              subPath: stash-origin-auth-scitokens.conf.local
            {{ end }}
            {{- if .Values.XrootdLogVolume }}
            - mountPath: /var/log/xrootd
              name: logs
            {{ end }}
          # end volumeMounts

# vim:et:sw=2:sts=2:ts=8
